package com.huangwenbin.demoapi.entity.generateentity;

import java.util.Date;

public class PermissionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_id
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_url
     *
     * @mbggenerated
     */
    private String permissionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_name
     *
     * @mbggenerated
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_status
     *
     * @mbggenerated
     */
    private Byte permissionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_type
     *
     * @mbggenerated
     */
    private Byte permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_parentid
     *
     * @mbggenerated
     */
    private Long permissionParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_createuser
     *
     * @mbggenerated
     */
    private Long permissionCreateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_createdate
     *
     * @mbggenerated
     */
    private Date permissionCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_modifyuser
     *
     * @mbggenerated
     */
    private Long permissionModifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_modifydate
     *
     * @mbggenerated
     */
    private Date permissionModifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_permission.permission_sortid
     *
     * @mbggenerated
     */
    private Long permissionSortid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_id
     *
     * @return the value of demo_permission.permission_id
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_id
     *
     * @param permissionId the value for demo_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_url
     *
     * @return the value of demo_permission.permission_url
     *
     * @mbggenerated
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_url
     *
     * @param permissionUrl the value for demo_permission.permission_url
     *
     * @mbggenerated
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_name
     *
     * @return the value of demo_permission.permission_name
     *
     * @mbggenerated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_name
     *
     * @param permissionName the value for demo_permission.permission_name
     *
     * @mbggenerated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_status
     *
     * @return the value of demo_permission.permission_status
     *
     * @mbggenerated
     */
    public Byte getPermissionStatus() {
        return permissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_status
     *
     * @param permissionStatus the value for demo_permission.permission_status
     *
     * @mbggenerated
     */
    public void setPermissionStatus(Byte permissionStatus) {
        this.permissionStatus = permissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_type
     *
     * @return the value of demo_permission.permission_type
     *
     * @mbggenerated
     */
    public Byte getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_type
     *
     * @param permissionType the value for demo_permission.permission_type
     *
     * @mbggenerated
     */
    public void setPermissionType(Byte permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_parentid
     *
     * @return the value of demo_permission.permission_parentid
     *
     * @mbggenerated
     */
    public Long getPermissionParentid() {
        return permissionParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_parentid
     *
     * @param permissionParentid the value for demo_permission.permission_parentid
     *
     * @mbggenerated
     */
    public void setPermissionParentid(Long permissionParentid) {
        this.permissionParentid = permissionParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_createuser
     *
     * @return the value of demo_permission.permission_createuser
     *
     * @mbggenerated
     */
    public Long getPermissionCreateuser() {
        return permissionCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_createuser
     *
     * @param permissionCreateuser the value for demo_permission.permission_createuser
     *
     * @mbggenerated
     */
    public void setPermissionCreateuser(Long permissionCreateuser) {
        this.permissionCreateuser = permissionCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_createdate
     *
     * @return the value of demo_permission.permission_createdate
     *
     * @mbggenerated
     */
    public Date getPermissionCreatedate() {
        return permissionCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_createdate
     *
     * @param permissionCreatedate the value for demo_permission.permission_createdate
     *
     * @mbggenerated
     */
    public void setPermissionCreatedate(Date permissionCreatedate) {
        this.permissionCreatedate = permissionCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_modifyuser
     *
     * @return the value of demo_permission.permission_modifyuser
     *
     * @mbggenerated
     */
    public Long getPermissionModifyuser() {
        return permissionModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_modifyuser
     *
     * @param permissionModifyuser the value for demo_permission.permission_modifyuser
     *
     * @mbggenerated
     */
    public void setPermissionModifyuser(Long permissionModifyuser) {
        this.permissionModifyuser = permissionModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_modifydate
     *
     * @return the value of demo_permission.permission_modifydate
     *
     * @mbggenerated
     */
    public Date getPermissionModifydate() {
        return permissionModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_modifydate
     *
     * @param permissionModifydate the value for demo_permission.permission_modifydate
     *
     * @mbggenerated
     */
    public void setPermissionModifydate(Date permissionModifydate) {
        this.permissionModifydate = permissionModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_permission.permission_sortid
     *
     * @return the value of demo_permission.permission_sortid
     *
     * @mbggenerated
     */
    public Long getPermissionSortid() {
        return permissionSortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_permission.permission_sortid
     *
     * @param permissionSortid the value for demo_permission.permission_sortid
     *
     * @mbggenerated
     */
    public void setPermissionSortid(Long permissionSortid) {
        this.permissionSortid = permissionSortid;
    }
}