package com.huangwenbin.demoapi.entity.generateentity;

import java.util.Date;

public class RoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_type
     *
     * @mbggenerated
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_status
     *
     * @mbggenerated
     */
    private Byte roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_createdate
     *
     * @mbggenerated
     */
    private Date roleCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_createuser
     *
     * @mbggenerated
     */
    private Long roleCreateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_modifyuser
     *
     * @mbggenerated
     */
    private Long roleModifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role.role_modifydate
     *
     * @mbggenerated
     */
    private Date roleModifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_id
     *
     * @return the value of demo_role.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_id
     *
     * @param roleId the value for demo_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_name
     *
     * @return the value of demo_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_name
     *
     * @param roleName the value for demo_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_type
     *
     * @return the value of demo_role.role_type
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_type
     *
     * @param roleType the value for demo_role.role_type
     *
     * @mbggenerated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_status
     *
     * @return the value of demo_role.role_status
     *
     * @mbggenerated
     */
    public Byte getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_status
     *
     * @param roleStatus the value for demo_role.role_status
     *
     * @mbggenerated
     */
    public void setRoleStatus(Byte roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_createdate
     *
     * @return the value of demo_role.role_createdate
     *
     * @mbggenerated
     */
    public Date getRoleCreatedate() {
        return roleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_createdate
     *
     * @param roleCreatedate the value for demo_role.role_createdate
     *
     * @mbggenerated
     */
    public void setRoleCreatedate(Date roleCreatedate) {
        this.roleCreatedate = roleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_createuser
     *
     * @return the value of demo_role.role_createuser
     *
     * @mbggenerated
     */
    public Long getRoleCreateuser() {
        return roleCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_createuser
     *
     * @param roleCreateuser the value for demo_role.role_createuser
     *
     * @mbggenerated
     */
    public void setRoleCreateuser(Long roleCreateuser) {
        this.roleCreateuser = roleCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_modifyuser
     *
     * @return the value of demo_role.role_modifyuser
     *
     * @mbggenerated
     */
    public Long getRoleModifyuser() {
        return roleModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_modifyuser
     *
     * @param roleModifyuser the value for demo_role.role_modifyuser
     *
     * @mbggenerated
     */
    public void setRoleModifyuser(Long roleModifyuser) {
        this.roleModifyuser = roleModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role.role_modifydate
     *
     * @return the value of demo_role.role_modifydate
     *
     * @mbggenerated
     */
    public Date getRoleModifydate() {
        return roleModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role.role_modifydate
     *
     * @param roleModifydate the value for demo_role.role_modifydate
     *
     * @mbggenerated
     */
    public void setRoleModifydate(Date roleModifydate) {
        this.roleModifydate = roleModifydate;
    }
}