package com.huangwenbin.demoapi.entity.generateentity;

import java.util.Date;

public class RolePermissionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    private Long rolePermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_rid
     *
     * @mbggenerated
     */
    private Long rolePermissionRid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_pid
     *
     * @mbggenerated
     */
    private Long rolePermissionPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_createdate
     *
     * @mbggenerated
     */
    private Date rolePermissionCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_createuser
     *
     * @mbggenerated
     */
    private Long rolePermissionCreateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_role_permission.role_permission_status
     *
     * @mbggenerated
     */
    private Byte rolePermissionStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_id
     *
     * @return the value of demo_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    public Long getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_id
     *
     * @param rolePermissionId the value for demo_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    public void setRolePermissionId(Long rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_rid
     *
     * @return the value of demo_role_permission.role_permission_rid
     *
     * @mbggenerated
     */
    public Long getRolePermissionRid() {
        return rolePermissionRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_rid
     *
     * @param rolePermissionRid the value for demo_role_permission.role_permission_rid
     *
     * @mbggenerated
     */
    public void setRolePermissionRid(Long rolePermissionRid) {
        this.rolePermissionRid = rolePermissionRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_pid
     *
     * @return the value of demo_role_permission.role_permission_pid
     *
     * @mbggenerated
     */
    public Long getRolePermissionPid() {
        return rolePermissionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_pid
     *
     * @param rolePermissionPid the value for demo_role_permission.role_permission_pid
     *
     * @mbggenerated
     */
    public void setRolePermissionPid(Long rolePermissionPid) {
        this.rolePermissionPid = rolePermissionPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_createdate
     *
     * @return the value of demo_role_permission.role_permission_createdate
     *
     * @mbggenerated
     */
    public Date getRolePermissionCreatedate() {
        return rolePermissionCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_createdate
     *
     * @param rolePermissionCreatedate the value for demo_role_permission.role_permission_createdate
     *
     * @mbggenerated
     */
    public void setRolePermissionCreatedate(Date rolePermissionCreatedate) {
        this.rolePermissionCreatedate = rolePermissionCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_createuser
     *
     * @return the value of demo_role_permission.role_permission_createuser
     *
     * @mbggenerated
     */
    public Long getRolePermissionCreateuser() {
        return rolePermissionCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_createuser
     *
     * @param rolePermissionCreateuser the value for demo_role_permission.role_permission_createuser
     *
     * @mbggenerated
     */
    public void setRolePermissionCreateuser(Long rolePermissionCreateuser) {
        this.rolePermissionCreateuser = rolePermissionCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_role_permission.role_permission_status
     *
     * @return the value of demo_role_permission.role_permission_status
     *
     * @mbggenerated
     */
    public Byte getRolePermissionStatus() {
        return rolePermissionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_role_permission.role_permission_status
     *
     * @param rolePermissionStatus the value for demo_role_permission.role_permission_status
     *
     * @mbggenerated
     */
    public void setRolePermissionStatus(Byte rolePermissionStatus) {
        this.rolePermissionStatus = rolePermissionStatus;
    }
}