package com.huangwenbin.demoapi.entity.generateentity;

import java.util.Date;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_truename
     *
     * @mbggenerated
     */
    private String userTruename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_nickname
     *
     * @mbggenerated
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_mobile
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_create_time
     *
     * @mbggenerated
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user__last_login_time
     *
     * @mbggenerated
     */
    private Date userLastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_status
     *
     * @mbggenerated
     */
    private Byte userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_url
     *
     * @mbggenerated
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_external_id
     *
     * @mbggenerated
     */
    private String userExternalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_modifydate
     *
     * @mbggenerated
     */
    private Date userModifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_id
     *
     * @return the value of demo_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_id
     *
     * @param userId the value for demo_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_truename
     *
     * @return the value of demo_user.user_truename
     *
     * @mbggenerated
     */
    public String getUserTruename() {
        return userTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_truename
     *
     * @param userTruename the value for demo_user.user_truename
     *
     * @mbggenerated
     */
    public void setUserTruename(String userTruename) {
        this.userTruename = userTruename == null ? null : userTruename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_nickname
     *
     * @return the value of demo_user.user_nickname
     *
     * @mbggenerated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_nickname
     *
     * @param userNickname the value for demo_user.user_nickname
     *
     * @mbggenerated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_email
     *
     * @return the value of demo_user.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_email
     *
     * @param userEmail the value for demo_user.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_mobile
     *
     * @return the value of demo_user.user_mobile
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_mobile
     *
     * @param userMobile the value for demo_user.user_mobile
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_password
     *
     * @return the value of demo_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_password
     *
     * @param userPassword the value for demo_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_create_time
     *
     * @return the value of demo_user.user_create_time
     *
     * @mbggenerated
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_create_time
     *
     * @param userCreateTime the value for demo_user.user_create_time
     *
     * @mbggenerated
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user__last_login_time
     *
     * @return the value of demo_user.user__last_login_time
     *
     * @mbggenerated
     */
    public Date getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user__last_login_time
     *
     * @param userLastLoginTime the value for demo_user.user__last_login_time
     *
     * @mbggenerated
     */
    public void setUserLastLoginTime(Date userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_status
     *
     * @return the value of demo_user.user_status
     *
     * @mbggenerated
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_status
     *
     * @param userStatus the value for demo_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_url
     *
     * @return the value of demo_user.user_url
     *
     * @mbggenerated
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_url
     *
     * @param userUrl the value for demo_user.user_url
     *
     * @mbggenerated
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl == null ? null : userUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_external_id
     *
     * @return the value of demo_user.user_external_id
     *
     * @mbggenerated
     */
    public String getUserExternalId() {
        return userExternalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_external_id
     *
     * @param userExternalId the value for demo_user.user_external_id
     *
     * @mbggenerated
     */
    public void setUserExternalId(String userExternalId) {
        this.userExternalId = userExternalId == null ? null : userExternalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_modifydate
     *
     * @return the value of demo_user.user_modifydate
     *
     * @mbggenerated
     */
    public Date getUserModifydate() {
        return userModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_modifydate
     *
     * @param userModifydate the value for demo_user.user_modifydate
     *
     * @mbggenerated
     */
    public void setUserModifydate(Date userModifydate) {
        this.userModifydate = userModifydate;
    }
}