package com.huangwenbin.demoapi.entity.generateentity;

import java.util.Date;

public class UserRoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_id
     *
     * @mbggenerated
     */
    private Long userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_uid
     *
     * @mbggenerated
     */
    private Long userRoleUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_rid
     *
     * @mbggenerated
     */
    private Long userRoleRid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_status
     *
     * @mbggenerated
     */
    private Byte userRoleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_createuser
     *
     * @mbggenerated
     */
    private Long userRoleCreateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_createdate
     *
     * @mbggenerated
     */
    private Date userRoleCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_modifyuser
     *
     * @mbggenerated
     */
    private Long userRoleModifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user_role.user_role_modifydate
     *
     * @mbggenerated
     */
    private Date userRoleModifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_id
     *
     * @return the value of demo_user_role.user_role_id
     *
     * @mbggenerated
     */
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_id
     *
     * @param userRoleId the value for demo_user_role.user_role_id
     *
     * @mbggenerated
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_uid
     *
     * @return the value of demo_user_role.user_role_uid
     *
     * @mbggenerated
     */
    public Long getUserRoleUid() {
        return userRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_uid
     *
     * @param userRoleUid the value for demo_user_role.user_role_uid
     *
     * @mbggenerated
     */
    public void setUserRoleUid(Long userRoleUid) {
        this.userRoleUid = userRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_rid
     *
     * @return the value of demo_user_role.user_role_rid
     *
     * @mbggenerated
     */
    public Long getUserRoleRid() {
        return userRoleRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_rid
     *
     * @param userRoleRid the value for demo_user_role.user_role_rid
     *
     * @mbggenerated
     */
    public void setUserRoleRid(Long userRoleRid) {
        this.userRoleRid = userRoleRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_status
     *
     * @return the value of demo_user_role.user_role_status
     *
     * @mbggenerated
     */
    public Byte getUserRoleStatus() {
        return userRoleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_status
     *
     * @param userRoleStatus the value for demo_user_role.user_role_status
     *
     * @mbggenerated
     */
    public void setUserRoleStatus(Byte userRoleStatus) {
        this.userRoleStatus = userRoleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_createuser
     *
     * @return the value of demo_user_role.user_role_createuser
     *
     * @mbggenerated
     */
    public Long getUserRoleCreateuser() {
        return userRoleCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_createuser
     *
     * @param userRoleCreateuser the value for demo_user_role.user_role_createuser
     *
     * @mbggenerated
     */
    public void setUserRoleCreateuser(Long userRoleCreateuser) {
        this.userRoleCreateuser = userRoleCreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_createdate
     *
     * @return the value of demo_user_role.user_role_createdate
     *
     * @mbggenerated
     */
    public Date getUserRoleCreatedate() {
        return userRoleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_createdate
     *
     * @param userRoleCreatedate the value for demo_user_role.user_role_createdate
     *
     * @mbggenerated
     */
    public void setUserRoleCreatedate(Date userRoleCreatedate) {
        this.userRoleCreatedate = userRoleCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_modifyuser
     *
     * @return the value of demo_user_role.user_role_modifyuser
     *
     * @mbggenerated
     */
    public Long getUserRoleModifyuser() {
        return userRoleModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_modifyuser
     *
     * @param userRoleModifyuser the value for demo_user_role.user_role_modifyuser
     *
     * @mbggenerated
     */
    public void setUserRoleModifyuser(Long userRoleModifyuser) {
        this.userRoleModifyuser = userRoleModifyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user_role.user_role_modifydate
     *
     * @return the value of demo_user_role.user_role_modifydate
     *
     * @mbggenerated
     */
    public Date getUserRoleModifydate() {
        return userRoleModifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user_role.user_role_modifydate
     *
     * @param userRoleModifydate the value for demo_user_role.user_role_modifydate
     *
     * @mbggenerated
     */
    public void setUserRoleModifydate(Date userRoleModifydate) {
        this.userRoleModifydate = userRoleModifydate;
    }
}