package com.huangwenbin.demoapi.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.huangwenbin.demoapi.entity.generateentity.PermissionEntity;

/**
 * Interface description
 *
 *
 * @version        1.0.0.0, 17/10/27
 * @author         huangwenbin
 */
@Mapper
public interface PermissionMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param permissionId
     *
     * @return
     */
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param record
     *
     * @return
     */
    int insert(PermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param record
     *
     * @return
     */
    int insertSelective(PermissionEntity record);

    /**
     * Method description
     *
     *
     * @return
     */
    List<PermissionEntity> queryAllPermission();

    /**
     * Method description
     *
     *
     * @param roleId
     *
     * @return
     */
    List<PermissionEntity> queryPermissionByRoleId(Long roleId);

    /**
     * Method description
     *
     *
     * @param userid
     *
     * @return
     */
    List<PermissionEntity> queryPermissionByUid(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param permissionId
     *
     * @return
     */
    PermissionEntity selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param record
     *
     * @return
     */
    int updateByPrimaryKey(PermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_permission
     *
     * @mbggenerated
     *
     * @param record
     *
     * @return
     */
    int updateByPrimaryKeySelective(PermissionEntity record);
}


//~ Formatted by Jindent --- http://www.jindent.com
