package com.huangwenbin.demoapi.mapper;

import com.huangwenbin.demoapi.entity.generateentity.RolePermissionEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * Interface description
 *
 * @author huangwenbin
 * @version 1.0.0.0, 17/11/01
 */
@Mapper
public interface RolePermissionMapper {

    /**
     * Method description
     *
     * @param rolePermissionEntityList
     * @return
     */
    int BatchInsert(List<RolePermissionEntity> rolePermissionEntityList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param rolePermissionId
     * @return
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insert(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insertSelective(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param rolePermissionId
     * @return
     * @mbggenerated
     */
    RolePermissionEntity selectByPrimaryKey(Long rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKey(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role_permission
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RolePermissionEntity record);

    /**
     * Method description
     *
     * @param roleId
     * @return
     */
    int updatePermissionToNoUseByRoleId(Long roleId);
}


//~ Formatted by Jindent --- http://www.jindent.com
