package com.huangwenbin.demoapi.mapper;

import java.util.List;
import java.util.Map;

import com.huangwenbin.demoapi.entity.generateentity.RoleEntity;
import org.apache.ibatis.annotations.Mapper;

/**
 * Interface description
 *
 * @author huangwenbin
 * @version 1.0.0.0, 17/10/31
 */
@Mapper
public interface RoleMapper {

    /**
     * Method description
     *
     * @param searchMap
     * @return
     */
    int countRole(Map<String, Long> searchMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param roleId
     * @return
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insertSelective(RoleEntity record);

    /**
     * Method description
     *
     * @return
     */
    List<RoleEntity> queryAllRole();

    /**
     * Method description
     *
     * @param searchMap
     * @return
     */
    List<RoleEntity> queryRole(Map<String, Long> searchMap);

    /**
     * Method description
     *
     * @param userRoleUid
     * @return
     */
    List<RoleEntity> queryRoleByUid(Long userRoleUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param roleId
     * @return
     * @mbggenerated
     */
    RoleEntity selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleEntity record);
}


//~ Formatted by Jindent --- http://www.jindent.com
