package com.huangwenbin.demoapi.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.huangwenbin.demoapi.entity.generateentity.UserEntity;

/**
 * Interface description
 *
 * @author huangwenbin
 * @version 1.0.0.0, 17/10/31
 */
@Mapper
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param userId
     * @return
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insertSelective(UserEntity record);

    /**
     * Method description
     *
     * @param filterString
     * @return
     */
    List<UserEntity> queryFilterUser(String filterString);

    /**
     * Method description
     *
     * @param account
     * @return
     */
    List<UserEntity> queryUserByAccount(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param userId
     * @return
     * @mbggenerated
     */
    UserEntity selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKey(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserEntity record);
}


//~ Formatted by Jindent --- http://www.jindent.com
