package com.huangwenbin.demoapi.mapper;

import com.huangwenbin.demoapi.entity.generateentity.UserRoleEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.Map;

/**
 * Interface description
 *
 * @author huangwenbin
 * @version 1.0.0.0, 17/11/01
 */
@Mapper
public interface UserRoleMapper {

    /**
     * Method description
     *
     * @param searchMap
     * @return
     */
    int countUserInRole(Map<String, Long> searchMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param userRoleId
     * @return
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insert(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int insertSelective(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param userRoleId
     * @return
     * @mbggenerated
     */
    UserRoleEntity selectByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user_role
     *
     * @param record
     * @return
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleEntity record);

    /**
     * Method description
     *
     * @param userRoleEntity
     * @return
     */
    int updateByUserIdAndRoleId(UserRoleEntity userRoleEntity);
}


//~ Formatted by Jindent --- http://www.jindent.com
